# Generated by Django 2.2.3 on 2019-11-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chirp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
